import Footer from "../Footer";
import Navbar from "../Navbar";
import Head from "next/head";

type Props = {
  children: JSX.Element;
};

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container">{children}</main>
      <Footer />
    </>
  );
};
export default Layout;
